name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  npm_audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: node --version
      - run: npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Run Test Cases
        run: npm run test 

      - name: Run Lint Checks
        run: npm run lint 
